<script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('plugins/webticker/webticker.min.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
<script src="{{ asset('plugins/jquery-ui/jquery-ui.min.js') }}"></script>
<script src="{{ asset('plugins/magnific-popup/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('plugins/carousel/owl.carousel.min.js') }}"></script>
<script src="{{ asset('plugins/wow/wow.min.js') }}"></script>
<script src="{{ asset('plugins/select2/select2.full.js') }}"></script>
<script src="{{ asset('plugins/sweetalert2/sweetalert2.min.js') }}"></script>
<script src="{{ asset('plugins/jquery/jquery.waypoints.min.js') }}"></script>
<script src="{{ asset('dist/js/custom.js') }}"></script>
